/* eslint-disable global-require */
const words = {
	setA: [
		{
			word: 'cry',
			translation: 'плакать',
			image: require('../assets/img/action(setA)/cry.jpg'),
			audioSrc: '../../../assets/audio/action(setA)/cry.mp3',
		},
		{
			word: 'dance',
			translation: 'танцевать',
			image: require('../assets/img/action(setA)/dance.jpg'),
			audioSrc: '../../../assets/audio/action(setA)/dance.mp3',
		},
		{
			word: 'dive',
			translation: 'нырять',
			image: require('../assets/img/action(setA)/dive.jpg'),
			audioSrc: '../../../assets/audio/action(setA)/dive.mp3',
		},
		{
			word: 'draw',
			translation: 'рисовать',
			image: require('../assets/img/action(setA)/draw.jpg'),
			audioSrc: '../../../assets/audio/action(setA)/draw.mp3',
		},
		{
			word: 'fish',
			translation: 'ловить рыбу',
			image: require('../assets/img/action(setA)/fish.jpg'),
			audioSrc: '../../../assets/audio/action(setA)/fish.mp3',
		},
		{
			word: 'fly',
			translation: 'летать',
			image: require('../assets/img/action(setA)/fly.jpg'),
			audioSrc: '../../../assets/audio/action(setA)/fly.mp3',
		},
		{
			word: 'hug',
			translation: 'обнимать',
			image: require('../assets/img/action(setA)/hug.jpg'),
			audioSrc: '../../../assets/audio/action(setA)/hug.mp3',
		},
		{
			word: 'jump',
			translation: 'прыгать',
			image: require('../assets/img/action(setA)/jump.jpg'),
			audioSrc: '../../../assets/audio/action(setA)/jump.mp3',
		},
	],
	setB: [
		{
			word: 'open',
			translation: 'открывать',
			image: require('../assets/img/action(setB)/open.jpg'),
			audioSrc: '../../../assets/audio/action(setB)/open.mp3',
		},
		{
			word: 'play',
			translation: 'играть',
			image: require('../assets/img/action(setB)/play.jpg'),
			audioSrc: '../../../assets/audio/action(setB)/play.mp3',
		},
		{
			word: 'point',
			translation: 'указывать',
			image: require('../assets/img/action(setB)/point.jpg'),
			audioSrc: '../../../assets/audio/action(setB)/point.mp3',
		},
		{
			word: 'ride',
			translation: 'ездить',
			image: require('../assets/img/action(setB)/ride.jpg'),
			audioSrc: '../../../assets/audio/action(setB)/ride.mp3',
		},
		{
			word: 'run',
			translation: 'бегать',
			image: require('../assets/img/action(setB)/run.jpg'),
			audioSrc: '../../../assets/audio/action(setB)/run.mp3',
		},
		{
			word: 'sing',
			translation: 'петь',
			image: require('../assets/img/action(setB)/sing.jpg'),
			audioSrc: '../../../assets/audio/action(setB)/sing.mp3',
		},
		{
			word: 'skip',
			translation: 'пропускать, прыгать',
			image: require('../assets/img/action(setB)/skip.jpg'),
			audioSrc: '../../../assets/audio/action(setB)/skip.mp3',
		},
		{
			word: 'swim',
			translation: 'плавать',
			image: require('../assets/img/action(setB)/swim.jpg'),
			audioSrc: '../../../assets/audio/action(setB)/swim.mp3',
		},
	],
	setC: [
		{
			word: 'argue',
			translation: 'спорить',
			image: require('../assets/img/action(setC)/argued.jpg'),
			audioSrc: '../../../assets/audio/action(setC)/argue.mp3',
		},
		{
			word: 'build',
			translation: 'строить',
			image: require('../assets/img/action(setC)/build.jpg'),
			audioSrc: '../../../assets/audio/action(setC)/build.mp3',
		},
		{
			word: 'carry',
			translation: 'нести',
			image: require('../assets/img/action(setC)/carry.jpg'),
			audioSrc: '../../../assets/audio/action(setC)/carry.mp3',
		},
		{
			word: 'catch',
			translation: 'ловить',
			image: require('../assets/img/action(setC)/catch.jpg'),
			audioSrc: '../../../assets/audio/action(setC)/catch.mp3',
		},
		{
			word: 'drive',
			translation: 'водить машину',
			image: require('../assets/img/action(setC)/drive.jpg'),
			audioSrc: '../../../assets/audio/action(setC)/drive.mp3',
		},
		{
			word: 'drop',
			translation: 'падать',
			image: require('../assets/img/action(setC)/drop.jpg'),
			audioSrc: '../../../assets/audio/action(setC)/drop.mp3',
		},
		{
			word: 'push',
			translation: 'толкать',
			image: require('../assets/img/action(setC)/push.jpg'),
			audioSrc: '../../../assets/audio/action(setC)/push.mp3',
		},
		{
			word: 'pull',
			translation: 'тянуть',
			image: require('../assets/img/action(setC)/pull.jpg'),
			audioSrc: '../../../assets/audio/action(setC)/pull.mp3',
		},
	],
	adjective: [
		{
			word: 'big',
			translation: 'большой',
			image: require('../assets/img/Adjective/big.jpg'),
			audioSrc: '../../../assets/audio/Adjective/big.mp3',
		},
		{
			word: 'small',
			translation: 'маленький',
			image: require('../assets/img/Adjective/small.jpg'),
			audioSrc: '../../../assets/audio/Adjective/small.mp3',
		},
		{
			word: 'fast',
			translation: 'быстрый',
			image: require('../assets/img/Adjective/fast.jpg'),
			audioSrc: '../../../assets/audio/Adjective/fast.mp3',
		},
		{
			word: 'slow',
			translation: 'медленный',
			image: require('../assets/img/Adjective/slow.jpg'),
			audioSrc: '../../../assets/audio/Adjective/slow.mp3',
		},
		{
			word: 'friendly',
			translation: 'дружелюбный',
			image: require('../assets/img/Adjective/friendly.jpg'),
			audioSrc: '../../../assets/audio/Adjective/friendly.mp3',
		},
		{
			word: 'unfriendly',
			translation: 'недружелюбный',
			image: require('../assets/img/Adjective/unfriendly.jpg'),
			audioSrc: '../../../assets/audio/Adjective/unfriendly.mp3',
		},
		{
			word: 'young',
			translation: 'молодой',
			image: require('../assets/img/Adjective/young.jpg'),
			audioSrc: '../../../assets/audio/Adjective/young.mp3',
		},
		{
			word: 'old',
			translation: 'старый',
			image: require('../assets/img/Adjective/old.jpg'),
			audioSrc: '../../../assets/audio/Adjective/old.mp3',
		},
	],
	setD: [
		{
			word: 'cat',
			translation: 'кот',
			image: require('../assets/img/Animal(setA)/cat.jpg'),
			audioSrc: '../../../assets/audio/Animal(setA)/cat.mp3',
		},
		{
			word: 'chick',
			translation: 'цыплёнок',
			image: require('../assets/img/Animal(setA)/chick.jpg'),
			audioSrc: '../../../assets/audio/Animal(setA)/chick.mp3',
		},
		{
			word: 'chicken',
			translation: 'курица',
			image: require('../assets/img/Animal(setA)/chicken.jpg'),
			audioSrc: '../../../assets/audio/Animal(setA)/chicken.mp3',
		},
		{
			word: 'dog',
			translation: 'собака',
			image: require('../assets/img/Animal(setA)/dog.jpg'),
			audioSrc: '../../../assets/audio/Animal(setA)/dog.mp3',
		},
		{
			word: 'horse',
			translation: 'лошадь',
			image: require('../assets/img/Animal(setA)/horse.jpg'),
			audioSrc: '../../../assets/audio/Animal(setA)/horse.mp3',
		},
		{
			word: 'pig',
			translation: 'свинья',
			image: require('../assets/img/Animal(setA)/pig.jpg'),
			audioSrc: '../../../assets/audio/Animal(setA)/pig.mp3',
		},
		{
			word: 'rabbit',
			translation: 'кролик',
			image: require('../assets/img/Animal(setA)/rabbit.jpg'),
			audioSrc: '../../../assets/audio/Animal(setA)/rabbit.mp3',
		},
		{
			word: 'sheep',
			translation: 'овца',
			image: require('../assets/img/Animal(setA)/sheep.jpg'),
			audioSrc: '../../../assets/audio/Animal(setA)/sheep.mp3',
		},
	],
	setI: [
		{
			word: 'bird',
			translation: 'птица',
			image: require('../assets/img/Animal(setB)/bird.jpg'),
			audioSrc: '../../../assets/audio/Animal(setB)/bird.mp3',
		},
		{
			word: 'fish',
			translation: 'рыба',
			image: require('../assets/img/Animal(setB)/fish1.jpg'),
			audioSrc: '../../../assets/audio/Animal(setB)/fish.mp3',
		},
		{
			word: 'frog',
			translation: 'жаба',
			image: require('../assets/img/Animal(setB)/frog.jpg'),
			audioSrc: '../../../assets/audio/Animal(setB)/frog.mp3',
		},
		{
			word: 'giraffe',
			translation: 'жираф',
			image: require('../assets/img/Animal(setB)/giraffe.jpg'),
			audioSrc: '../../../assets/audio/Animal(setB)/giraffe.mp3',
		},
		{
			word: 'lion',
			translation: 'лев',
			image: require('../assets/img/Animal(setB)/lion.jpg'),
			audioSrc: '../../../assets/audio/Animal(setB)/lion.mp3',
		},
		{
			word: 'mouse',
			translation: 'мышь',
			image: require('../assets/img/Animal(setB)/mouse.jpg'),
			audioSrc: '../../../assets/audio/Animal(setB)/mouse.mp3',
		},
		{
			word: 'turtle',
			translation: 'черепаха',
			image: require('../assets/img/Animal(setB)/turtle.jpg'),
			audioSrc: '../../../assets/audio/Animal(setB)/turtle.mp3',
		},
		{
			word: 'dolphin',
			translation: 'дельфин',
			image: require('../assets/img/Animal(setB)/dolphin.jpg'),
			audioSrc: '../../../assets/audio/Animal(setB)/dolphin.mp3',
		},
	],
	clothes: [
		{
			word: 'skirt',
			translation: 'юбка',
			image: require('../assets/img/Clothes/skirt.jpg'),
			audioSrc: '../../../assets/audio/Clothes/skirt.mp3',
		},
		{
			word: 'pants',
			translation: 'брюки',
			image: require('../assets/img/Clothes/pants.jpg'),
			audioSrc: '../../../assets/audio/Clothes/pants.mp3',
		},
		{
			word: 'blouse',
			translation: 'блузка',
			image: require('../assets/img/Clothes/blouse.jpg'),
			audioSrc: '../../../assets/audio/Clothes/blouse.mp3',
		},
		{
			word: 'dress',
			translation: 'платье',
			image: require('../assets/img/Clothes/dress.jpg'),
			audioSrc: '../../../assets/audio/Clothes/dress.mp3',
		},
		{
			word: 'boot',
			translation: 'ботинок',
			image: require('../assets/img/Clothes/boot.jpg'),
			audioSrc: '../../../assets/audio/Clothes/boot.mp3',
		},
		{
			word: 'shirt',
			translation: 'рубашка',
			image: require('../assets/img/Clothes/shirt.jpg'),
			audioSrc: '../../../assets/audio/Clothes/shirt.mp3',
		},
		{
			word: 'coat',
			translation: 'пальто',
			image: require('../assets/img/Clothes/coat.jpg'),
			audioSrc: '../../../assets/audio/Clothes/coat.mp3',
		},
		{
			word: 'shoe',
			translation: 'туфли',
			image: require('../assets/img/Clothes/shoe.jpg'),
			audioSrc: '../../../assets/audio/Clothes/shoe.mp3',
		},
	],
	emotion: [
		{
			word: 'sad',
			translation: 'грустный',
			image: require('../assets/img/Emotion/sad.jpg'),
			audioSrc: '../../../assets/audio/Emotion/sad.mp3',
		},
		{
			word: 'angry',
			translation: 'сердитый',
			image: require('../assets/img/Emotion/angry.jpg'),
			audioSrc: '../../../assets/audio/Emotion/angry.mp3',
		},
		{
			word: 'happy',
			translation: 'счастливый',
			image: require('../assets/img/Emotion/happy.jpg'),
			audioSrc: '../../../assets/audio/Emotion/happy.mp3',
		},
		{
			word: 'tired',
			translation: 'уставший',
			image: require('../assets/img/Emotion/tired.jpg'),
			audioSrc: '../../../assets/audio/Emotion/tired.mp3',
		},
		{
			word: 'surprised',
			translation: 'удивлённый',
			image: require('../assets/img/Emotion/surprised.jpg'),
			audioSrc: '../../../assets/audio/Emotion/surprised.mp3',
		},
		{
			word: 'scared',
			translation: 'испуганный',
			image: require('../assets/img/Emotion/scared.jpg'),
			audioSrc: '../../../assets/audio/Emotion/scared.mp3',
		},
		{
			word: 'smile',
			translation: 'улыбка',
			image: require('../assets/img/Emotion/smile.jpg'),
			audioSrc: '../../../assets/audio/Emotion/smile.mp3',
		},
		{
			word: 'laugh',
			translation: 'смех',
			image: require('../assets/img/Emotion/laugh.jpg'),
			audioSrc: '../../../assets/audio/Emotion/laugh.mp3',
		},
	],
}

export default words
